### ISSUE TITLE
Can't run my device with Leku versions > 3.4.5

### ISSUE THREAD

**Issue by yeray697** [SchibstedSpain/Leku#132]
## Description
It works fine with 3.4.5, but in pre lollipop device gives me ClassNotFoundException, so I decided to upgrade Leku to the newest
The problem is that it doens't compile.
I'm using Java 8
I've also tried to clean project, invalidating cache and restarting and removing manually .gradle/cache

(I'll test it later with a clean project)

## Info Required

- Which version of the library do you actually use?
3.6.2

- Do you have the localization permission granted?
Yes

- Are you sending parameters to the activity through the bundle?

- Could you describe what are the actions do you make to raise that error?
Compiling and running in device

- Android monitor shows any log related to the library when the error is shown?
Gradle messages
![error_leku](https://user-images.githubusercontent.com/16388317/34610049-9c901de2-f21f-11e7-963b-c01c166e7210.png)

[Full Gradle Console messages run with --stacktrace ](https://pastebin.com/A4BZMnWU)

- Any other thing that could help me to reproduce the error?
Gradle configuration:
```
android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'
    defaultConfig {
        applicationId "-"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode -
        versionName "-"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
```

**Comment by aymenhs** [comment]
I got I think the same message, but for me it's the first time I use it just by following tutorial here.

![error](https://user-images.githubusercontent.com/1870186/34652487-1e408744-f3df-11e7-9d4a-08af78307376.png)

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "xxxx"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }

and 
compile 'com.schibstedspain.android:leku:3.6.2'


any help please? thanks

**Comment by rahuldange09** [comment]
Anyone got solution? facing same problem

> `Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing com/schibstedspain/leku/geocoder/AndroidGeocoderDataSource.class
Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\LENOVO\.gradle\caches\transforms-1\files-1.1\Leku-v3.6.1.aar\62f61824453626d1b8a315182ef0c4e7\jars\classes.jar`

**Comment by ferranpons** [comment]
@yeray697 @aymenhs @rahuldange09 are you using the new D8 dexer?

Because this looks like an error with the D8, it's not working very well. Please try to add to your build file `gradle.properties` this line:

`android.enableD8=false`

**Comment by yeray697** [comment]
Well, adding that line gives me less errors, but setting enableD8 to true works.
Anyway, it still gives me an error while building intent
`Intent i = new LocationPickerActivity.Builder()
                .withGeolocApiKey(getString(R.string.google_maps_key))
                .withSearchZone("es_ES")
                .build(getContext());`

Error:
`java.lang.NoClassDefFoundError: com.schibstedspain.leku.LocationPickerActivity
                                                                  at com.schibstedspain.leku.LocationPickerActivity$Builder.build(LocationPickerActivity.java:1143)`

**Comment by rahuldange09** [comment]
@ferrangrau as @yeray697 said same happening here
changed android.enableD8=true solved that issue
but as @yeray697 mentioned getting same error now

**Comment by ferranpons** [comment]
@rahuldange09 @yeray697 that's strange. Because different classes are failing without a reason. Please could you tell me which version of Play Services are you using? And which devices are you experiencing this issue? Are you using proguard?

**Comment by rahuldange09** [comment]
@ferrangrau 
**Version of Play Services**
gms11.8.0(gradle) / 11.9.73(device) 

**Device**
 Xiaomi Redmi Note4 but with Custom rom

 **Are you using proguard?**
Not In debug mode

**Comment by ferranpons** [comment]
@rahuldange09 have you tried with the emulator? Because If the device is rooted and you're using a custom rom I can't figure out how to solve the problem and I can't give you support.

**Comment by yeray697** [comment]
I’ve tried with both, I don’t know if the physical device is rooted or not
Could be the new android studio version the problem?

**Comment by ferranpons** [comment]
@yeray697 are you using a "canary" version or the stable one?

**Comment by yeray697** [comment]
Stable version, but I haven't got a similar error pre 3.0

**Comment by rahuldange09** [comment]
@ferrangrau Tried on other devices still same
yes i'm also in stable version of Android Studio

**Comment by yeray697** [comment]
I have no physical device to test right now, but with emulator i'm not able to get an address with 
```
new Geocoder(getContext(), Locale.getDefault())
                    .getFromLocation(latitude, longitude, 1)
```
but I was able to get it with higher versions, I don't know if it's related to the same error (?)

**Comment by rahuldange09** [comment]
@yeray697 

> NoClassDefFoundError

this error solved for you?

**Comment by yeray697** [comment]
Not yet

**Comment by rahuldange09** [comment]
But in this you said

```
I have no physical device to test right now, but with emulator i'm not able to get an address with

new Geocoder(getContext(), Locale.getDefault())
                    .getFromLocation(latitude, longitude, 1)
but I was able to get it with higher versions, I don't know if it's related to the same error (?)
```

This means that its working right?
you are just not able to get address. 
So you on older version?

**Comment by ferranpons** [comment]
@yeray697 if you're no able to get an address from the emulator is due to probably you're using an emulator without google apis. Also, geocoder could fail or not retrieve an address.

**Comment by ferranpons** [comment]
@rahuldange09 @yeray697 do you have a GeocoderPressenter class in your project? Becaude this could be another reason why Dex is failing.

BTW I'm @ferranpons and not @ferrangrau 😅

**Comment by rahuldange09** [comment]
@ferranpons I'm extremely  sorry... github recommendation.
 No i don't have GeocoderPressenter class in my project.

**Comment by ferranpons** [comment]
@rahuldange09 no worries 😉 

Do you have multidex enabled? That's the only thing could make this kind of error apart from the other things I asked before.

**Comment by rahuldange09** [comment]
@ferranpons  yes i have multidex enabled and tried after disabling it but still
with this error same mentioned above


```
  Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/OnMapReadyCallback;
at com.......getLocation(LoacationAccessActivity.java:226)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.maps.OnMapReadyCallback" on path: DexPathList
```

**Comment by ferranpons** [comment]
@rahuldange09 you don't have to disable multidex, It's needed if you surpass the limit of java classes. (65K)

Please, could you share the build.gradle without any sensible data?

**Comment by rahuldange09** [comment]
@ferranpons yes I enabled multidex again

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.name.myapp"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.android.support:design:27.0.2'
    implementation 'com.android.support:cardview-v7:27.0.2'
    implementation 'com.android.support:support-v4:27.0.2'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'


    implementation 'com.google.firebase:firebase-auth:11.8.0'
    implementation 'com.google.firebase:firebase-database:11.8.0'
    compile 'com.google.firebase:firebase-auth:11.8.0'
    compile 'com.google.android.gms:play-services-auth:11.8.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    compile 'com.ogaclejapan.smarttablayout:library:1.6.1@aar'
    //Optional: see how to use the utility.
    compile 'com.ogaclejapan.smarttablayout:utils-v4:1.6.1@aar'

    //Maps
    compile 'com.github.SchibstedSpain:Leku:v3.6.2'
 

 

    //Vertical
    compile 'me.kaelaela:verticalviewpager:1.0.0@aar'


    //rss
    compile 'com.github.faruktoptas:RetrofitRssConverterFactory:0.0.2'
    compile 'com.squareup.picasso:picasso:2.5.2'


}
```

**Comment by ferranpons** [comment]
@rahuldange09 I don't see anything strange. The only thing could be that you're targeting api 27 and the library is not supporting it for now (has api 26). So maybe you need to exclude support library and play services from the compile because will have conflicts for sure. Like:

```
implementation ('com.schibstedspain.android:leku:3.6.2') {
    exclude group: 'com.google.android.gms'
    exclude group: 'com.android.support'
}
```

**Comment by ferranpons** [comment]
BTW I'm upgrading the project to api 27 [https://github.com/SchibstedSpain/Leku/pull/135](https://github.com/SchibstedSpain/Leku/pull/135)

**Comment by ferranpons** [comment]
@rahuldange09 @yeray697 version 3.7.0 with api 27 and gms 11.8.0 now available for download.

```groovy
implementation ('com.schibstedspain.android:leku:3.7.0') {
    exclude group: 'com.google.android.gms'
    exclude group: 'com.android.support'
}
```

**Comment by rahuldange09** [comment]
@ferranpons thank you for your instant update
but SORRY strange is that 
that horrifying error is still same 🤕

**Comment by ferranpons** [comment]
@rahuldange09 I don't get it. The error is related with de Dexing process. 🤔 
Are you sure that you have implemented correctly multidex? I mean, do you extend your application class with `MultiDexApplication` or do you use the method `MultiDex.install(this);` on your `attachBaseContext` method? Or use the `android:name="android.support.multidex.MultiDexApplication"` on your manifest?
Any of these 3 possible things could make work correctly multidex.

I ask you this to discard more possibilities because I don't know where is the problem. 😕

**Comment by yeray697** [comment]
Well, I've been testing and Leku works good for me until 3.6.0.

This gradle is working for me, but not for >= 3.6.0

```
android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'
    defaultConfig {
        applicationId ""
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 
        versionName ""
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
}
...
dependencies {
    implementation 'com.schibstedspain.android:leku:3.5.0'
}
```

**Comment by ferranpons** [comment]
@yeray697 I don't know where could be the problem. I could ask you the same as I asked to @rahuldange09. Have you correctly implemented multidex?

Have you added a new library apart from updating Leku?

I'm getting without of ideas 😞

**Comment by yeray697** [comment]
I think so, I have  multiDexEnabled true and compile 'com.android.support:multidex:1.0.1', besides having my Application class extending from MultiDexApplication. I tried overriding attachBaseContext too (without extending) , but I still get the same error.
Did I skip some step?

No, I haven't added a new library

**Comment by ferranpons** [comment]
@rahuldange09 I have review your build.gradle again, you have duplicated this lines:

```
implementation 'com.google.firebase:firebase-auth:11.8.0'
implementation 'com.google.firebase:firebase-database:11.8.0'
compile 'com.google.firebase:firebase-auth:11.8.0'
compile 'com.google.android.gms:play-services-auth:11.8.0'
```

You only need the "implementation" lines. Compile is deprecated.

**Comment by ferranpons** [comment]
@yeray697 which error are you still experiencing? The "no class found" or Geocoder not retrieving location?

**Comment by yeray697** [comment]
I'm still geting java.lang.NoClassDefFoundError: com.schibstedspain.leku.LocationPickerActivity while using  >= 3.6.0

```
compileSdkVersion 27
    buildToolsVersion '27.0.2'
    defaultConfig {
        applicationId ""
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 
        versionName ""
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
    }

...

dependencies {
    ...
    def supportVersion = '27.0.2'
    def playServicesVersion = '11.8.0'
    implementation 'com.schibstedspain.android:leku:3.7.0'
    ...
}
```

**Comment by ferranpons** [comment]
@yeray697 Did you add the activity to the manifest? 🤔

**Comment by yeray697** [comment]
Yes, I have 
```
<activity
            android:name="com.schibstedspain.leku.LocationPickerActivity"
            android:label="@string/leku_title_activity_location_picker"
            android:parentActivityName=".view.activity.Home_Activity"
            android:theme="@style/AppTheme_LocationPicker"
            android:windowSoftInputMode="adjustPan">
            <intent-filter>
                <action android:name="android.intent.action.SEARCH" />
            </intent-filter>
            <meta-data android:name="android.app.searchable"
                android:resource="@xml/leku_searchable" />
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".view.activity.Home_Activity" />
</activity>
```
I'm doing some test, and in api 21 and 23 I get more information about the crash:
[https://pastebin.com/E2261HWv](https://pastebin.com/E2261HWv)


(By the way, you forgot to change on readme the leku prefix in `android:resource="@xml/searchable"`)

**Comment by ferranpons** [comment]
@yeray697 If you're using an emulator with api 21 it's possible that you have this kind of error because it has a bug with Instant Run. Are you using Instant Run? If you're using it please disable it and make a clean and rebuild project because it's probably not generating correctly the Dex path for your APK. Sounds weird but it happens.

**Comment by yeray697** [comment]
Sorr for the long delay for the response.
Yes, I've already disable Instant Run and it still fails.
I'm updating Android Studio in other computer to check if it's my laptop fault

**Comment by yeray697** [comment]
Well, I don't know what happened, but now it's working.
I was getting this warning `all com.android.support libraries must use the exact same version [...]`, I solved it, and now it's working, I don't know if that error can cause NoClassDefFoundError ¯\_(ツ)_/¯

Thanks for your support :)

**Comment by ferranpons** [comment]
@yeray697 good to know that is working now. 😉 

@rahuldange09 are you still experiencing this issue?

**Comment by yeray697** [comment]
I have good and bad news.
The bad one is that I got the error again (?)
The good one is that cloning it and importing it as a module to the project works good

I think it's android studio's fault.

Take a look to this solution @rahuldange09
