### ISSUE TITLE
v5.1.1   java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Midhilaj** [SchibstedSpain/Leku#206]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/maps/GeoApiContext$Builder;
   at com.schibstedspain.leku.LocationPickerActivity.setUpMainVariables(SourceFile:234)
        at com.schibstedspain.leku.LocationPickerActivity.onCreate(SourceFile:205)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.maps.GeoApiContext$Builder" on path: DexPathList[[zip file

[from github](https://github.com/googlemaps/google-maps-services-java/issues/309)

**Comment by ferranpons** [comment]
I'll check as soon as I can but for now please try to override the version that the library is actually using.

I mean using a version greater than "0.2.9", for example:

implementation "com.google.maps:google-maps-services:0.9.0"

And excluding it from the implementation of leku like:

implementation ('com.schibstedspain.android:leku:5.1.1') {
    exclude group: 'com.google.android.gms'
    exclude group: 'com.android.support'
    exclude group: 'com.google.maps'
}

**Comment by ferranpons** [comment]
Solved with the version 5.1.3. I'm closing this issue, it's also duplicated.
