### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by soad130** [SchibstedSpain/Leku#48]
Instructions unclear. dick stuck in freezer

`java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzab; or its super classes (declaration of 'com.google.android.gms.common.internal.zzab' appears in /data/app/mypackagename-2/base.apk)
                                                                     at com.google.android.gms.maps.model.CameraPosition.<init>(Unknown Source)
                                                                     at com.google.android.gms.maps.model.CameraPosition.<init>(Unknown Source)
                                                                     at com.google.android.gms.maps.model.CameraPosition$Builder.build(Unknown Source)
                                                                     at com.google.android.gms.maps.model.CameraPosition.createFromAttributes(Unknown Source)
                                                                     at com.google.android.gms.maps.GoogleMapOptions.createFromAttributes(Unknown Source)
                                                                     at com.google.android.gms.maps.SupportMapFragment.onInflate(Unknown Source)
                                                                     at android.support.v4.app.Fragment.onInflate(Fragment.java:1174)
                                                                     at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2414)
                                                                     at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
                                                                     at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:376)
                                                                     at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:33)
                                                                     at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:75)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                     at com.schibstedspain.leku.LocationPickerActivity.onCreate(LocationPickerActivity.java:112)
                                                                     at android.app.Activity.performCreate(Activity.java:5975)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:147)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5264)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)`

I followed the steps on main page. Is this happens because I try to start it from a fragment? Thx

edit: About that google-services stuff. I got this line at the bottom of my gradle file : 
apply plugin: 'com.google.gms.google-services'

classpath 'com.google.gms:google-services:3.0.0' // and this is in the other gradle file. Called project-level gradle file I think.

that was needed for firebase setup

**Comment by ferranpons** [comment]
Hi @soad130 

Sorry, but this issue it's not happening because you're trying to start it from a Fragment.

We need more info to try to understand what's happening to you. Please could you tell me which version of play-services are you using? And the device and it's version of android?

And please, if you are using the version 9.6.1 and above of play services, assure that you include google-places because it's needed for that version of play-services.

compile "com.google.android.gms:play-services-places:9.6.1"

Many thanks!

**Comment by ferranpons** [comment]
@soad130 I assume that this is not longer an issue for you so I close it; because you did not answer my question and didn't tell anything about it for a long time. If you consider that it's still a bug please reopen it again.

![giphy 46](https://cloud.githubusercontent.com/assets/1225463/20429979/156d2576-ad92-11e6-9159-53c185f633d6.gif)

**Comment by myinnos** [comment]
Am facing with same issue with Activity! 
`java.lang.NoSuchMethodError: No static method create(Lrx/Observable$OnSubscribe;)Lrx/Observable; in class Lrx/Observable; or its super classes (declaration of 'rx.Observable' appears in /data/data/in.pnplabs.babyonboard/files/instant-run/dex/slice-slice_6-classes.dex)
`
Let me know the solution!
