### ISSUE TITLE
java.lang.NoSuchMethodError: No static method com_schibstedspain_leku_LocationPicker...

### ISSUE THREAD

**Issue by nishantpardamwar** [SchibstedSpain/Leku#68]
## Description
using jack compiler, when trying to start LocationPickerActivity getting
**java.lang.NoSuchMethodError: No static method com_schibstedspain_leku_LocationPicker$$Lambda$1_lambda$static$0(Lcom/schibstedspain/leku/tracker/TrackEvents;)V in class Lcom/schibstedspain/leku/LocationPicker; or its super classes (declaration of 'com.schibstedspain.leku.LocationPicker' appears** 

- Which version of the library do you actually use?
       v3.0.0

- Do you have the localization permission granted?
  yes

- Are you sending parameters to the activity through the bundle?
   no

- Could you describe what are the actions do you make to raise that error?
  starting LocationPickerActivity

- Android monitor shows any log related to the library when the error is shown?
```
 java.lang.NoSuchMethodError: No static method com_schibstedspain_leku_LocationPicker$$Lambda$1_lambda$static$0(Lcom/schibstedspain/leku/tracker/TrackEvents;)V in class Lcom/schibstedspain/leku/LocationPicker; or its super classes (declaration of 'com.schibstedspain.leku.LocationPicker' appears in /data/app/in.co.c24customer-1/base.apk)
                                                                       at com.schibstedspain.leku.LocationPicker$$Lambda$1.onEventTracked(Unknown Source)
                                                                       at com.schibstedspain.leku.LocationPickerActivity.setTracking(LocationPickerActivity.java:142)
                                                                       at com.schibstedspain.leku.LocationPickerActivity.onCreate(LocationPickerActivity.java:132)
                                                                       at android.app.Activity.performCreate(Activity.java:6679)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by ferranpons** [comment]
Hi @nishantpardamwar 

Looks like a weird issue. The stack trace says that the method does not exist when it's bundled with the library. So I need more info about how is your app builded.

Please could you tell me, if you set an event tracker, how do you set it? For example, in the sample app is set in this way:

`
LocationPicker.setTracker(new LocationPickerTracker() {
      @Override
      public void onEventTracked(TrackEvents event) {
        Toast.makeText(MainActivity.this, "Event: " + event.getEventName(), Toast.LENGTH_SHORT)
            .show();
      }
    });
`
- Are you doing something like this?

- Also, do you have your own TrackEvents class? Or did you override it?

- This is happening in debug? or in release mode?

- Do you have the code added directly to your project? If so, do you have also the library in your gradle.build?


Many thanks!

**Comment by nishantpardamwar** [comment]
i have just added the lib in gradle and added manifest code and trying to start LocationPickerActivity, thats it no custom TrackEvents and also not setting setTracker().
btw i tried adding

`LocationPicker.setTracker(new LocationPickerTracker() { @Override public void onEventTracked(TrackEvents event) { Toast.makeText(MainActivity.this, "Event: " + event.getEventName(), Toast.LENGTH_SHORT) .show(); } });`

and now its showing this error
 ```


No static method com_schibstedspain_leku_geocoder_GeocoderInteractor$$Lambda$2_lambda$getFromLocationName$14(Lcom/schibstedspain/leku/geocoder/GeocoderInteractor;Ljava/lang/String;Lcom/google/android/gms/maps/model/LatLng;Lcom/google/android/gms/maps/model/LatLng;Lrx/Subscriber;)V in class Lcom/schibstedspain/leku/geocoder/GeocoderInteractor; or its super classes (declaration of 'com.schibstedspain.leku.geocoder.GeocoderInteractor' appears in /data/app/in.co.c24customer-1/base.apk)
                                                                     at com.schibstedspain.leku.geocoder.GeocoderInteractor$$Lambda$2.call(Unknown Source)
                                                                     at rx.Observable.unsafeSubscribe(Observable.java:10142)
                                                                     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                     at java.lang.Thread.run(Thread.java:761) 
```

**Comment by galadril** [comment]
this could be a multidex issue right?

to enable multidex (to test it):

add this line to your manifest file

```
<application
    ...
    android:name="android.support.multidex.MultiDexApplication">
    ...
</application>

```
and also add this to your gradle

```
defaultConfig {
    ...
    minSdkVersion 14
    targetSdkVersion 21
    ...

    // Enabling multidex support.
    multiDexEnabled true
}
```

**Second solution**

add this to your launcher activity's onCreate() method

```
public void onCreate(Bundle arguments) {
 Context context = this.getInstrumentation().getTargetContext().getApplicationContext();
  MultiDex.install(context );
  super.onCreate(arguments);
...
}
```

or

needed to add this in class that extends Application:

```
@Override
protected void attachBaseContext(Context base) {
    super.attachBaseContext(base);
    MultiDex.install(this);
}
```


Hope it works..

**Comment by ferranpons** [comment]
@nishantpardamwar do you still have the problem or what said @galadril solved it?

**Comment by ferranpons** [comment]
@nishantpardamwar I'm closing this issue because I got no response about it. If you still have this issue please reopen it. Thanks.

**Comment by CeccoCQ** [comment]
Hi @ferranpons , I have same issue.
I changed the compileOptions to VERSION_1_8. I see that "lambda" is a feature of Java 8, probably the error is related to this.

**Comment by jayakrishnan1236** [comment]
Similar issue

[ java.lang.NoSuchMethodError: No static method lambda$addListener](https://github.com/dji-sdk/Mobile-SDK-Android/issues/140)
